[WIP][SA-18] get list of friends from facebook in this app
SprainedAnkleApp/backend pull request #27
Opened 2021-05-12 18:55 UTC by Zhylkaaa

nowy endpoint /fb_friends zwracający listę znajomych z fb. Nie zadziała w przypadku gdy użytkownik nie logował się nigdy przez FB, na razie ustalamy jak to powinno być obsłużone.
Też ustalamy w jakim formacie chcemy dostarczać użytkowników w odpowiedzi na zapytania (na razie leci za dużo)

2021-05-12 19:19 UTC, Zhylkaaa commented
poprawiłem problem z użytkownikami nie zalogowanymi przez fb

2021-05-16 09:50 UTC, piotrpolec requested changes

2021-05-16 09:50 UTC, piotrpolec commented on src/main/java/pl/edu/agh/ki/io/api/UserApiController.java
> +import java.util.stream.Collectors;
Jak importujesz w 27 wszystko to 28 chyba jest niepotrzebna

2021-05-16 18:59 UTC, AlexMaz99 approved these changes

2021-05-16 21:34 UTC, merged