[SA-3, SA-46] add JWT login
SprainedAnkleApp/backend pull request #3
Opened 2021-03-25 04:54 UTC by Zhylkaaa

this pull request: 
- adds JWT authorisation for users stored in database
- adds small fixes to User, Gender and Peak models
- refactors project structure by placing config directory in Application context

2021-03-25 09:27 UTC, AlexMaz99 approved these changes

2021-03-25 11:58 UTC, piotrpolec requested changes

2021-03-25 12:05 UTC, Zhylkaaa commented on src/main/java/pl/edu/agh/ki/io/config/SecurityConfig.java
> +public class SecurityConfig extends WebSecurityConfigurerAdapter {
w jakim sensie? to jest konfiguracja która jest ogarniana przez Spring i injectowana tam gdzie jest potrzebna, więc teoretycznie to jest gdzieś tam ukryty Singleton chyba 🤷‍♂️

2021-03-25 12:08 UTC, Zhylkaaa commented on src/main/java/pl/edu/agh/ki/io/db/DbInit.java
> +    }
w sensie to jest tylko dla testów żeby wrzucić jakiegoś użytkownika do bazy (zauważ że potrzebujemy encoder haseł). I przy testach na lokalnej bazie to się przydaje, a przy użyciu bazy na GCP zakomentowałem to żeby nie stwarzać niepotrzebnych zapytań do bazy (usuwać i wstawiać z powrotem)

2021-03-25 12:10 UTC, Zhylkaaa commented on src/main/java/pl/edu/agh/ki/io/models/User.java
> +    private Set<User> friends = new HashSet<>();
widziałem że tak ludzie robią żeby nie dostać w którymś momencie NullPointer, albo coś takiego 
w tej klasie jest konstruktor pusty (wymagany) więc chyba inicjalizacja poza konstruktorem jest ok, ale poprawić mnie, bo się nie znam na konwencjach java

2021-03-25 12:19 UTC, piotrpolec commented on src/main/java/pl/edu/agh/ki/io/config/SecurityConfig.java
> +public class SecurityConfig extends WebSecurityConfigurerAdapter {
oki, w takim razie nieważne xd

2021-03-25 12:19 UTC, piotrpolec commented on src/main/java/pl/edu/agh/ki/io/db/DbInit.java
> +    }
Oki, możemy i tak rozważyć później zrobienie tego factory, przyda się do testów

2021-03-25 12:22 UTC, merged

2021-03-27 12:59 UTC, Zhylkaaa commented on src/main/java/pl/edu/agh/ki/io/db/DbInit.java
> +    }
to prawda, ale pewnie samo wyjdzie jak będziemy robili sing up