[SA-213] Background photo and profile picture updates
SprainedAnkleApp/backend pull request #53
Opened 2021-06-03 17:25 UTC by Zhylkaaa

* add background image
* small refactor od PeakPostsApiController
* optimize imports

2021-06-03 19:53 UTC, rafalsz98 approved these changes
Fajen

2021-06-09 18:36 UTC, Zhylkaaa commented
zmieniłem PeakPostStorage, bo moim zdaniem Storage nie może zwracać obiektów dto bo to jest abstrakcja nad bazą, więc musi zwracać obiekty entity

2021-06-10 15:47 UTC, piotrpolec approved these changes

2021-06-10 16:17 UTC, piotrpolec requested changes
Zwracasz peakpost zamiast peakpostresponse w get na wszystkich

2021-06-12 18:15 UTC, kdebiec approved these changes

2021-06-12 21:34 UTC, piotrpolec approved these changes

2021-06-12 21:34 UTC, merged